version: '3.8'

services:
  whatsapp-blast-dev:
    build: .
    container_name: wa-blast-dev
    ports:
      - "3000:3000"
    volumes:
      - ./auth_info_baileys:/app/auth_info_baileys
      - ./sessions:/app/sessions
      - ./server.js:/app/server.js
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: unless-stopped

networks:
  default:
    driver: bridge
